services:
  - type: web
    name: fizikon-misafirhane
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_DIR
        value: /opt/render/project/src/data
    disk:
      name: app-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
